Repository Requisitos-de-Software/2021.1-TesouroDireto, pull requests merged in 2021-08, with the labels that each got.

#10 Criação do documento de introspecção.
  docs/introspeccao.md
  mkdocs.yml
Labels: documentation, elicitação

#12 8 analise protocolo
  docs/elicitacao/analise_protocolo.md
Labels: documentation, elicitação

#13 1 personas
  docs/assets/Persona1.jpeg
  docs/assets/Persona2.jpeg
  docs/assets/Persona3.jpeg
  docs/assets/Persona4.jpeg
  docs/personas.md
  mkdocs.yml
Labels: documentation, elicitação

#15 Obs part
  docs/observacao_participativa.md
  mkdocs.yml
Labels: documentation, elicitação

#19 Criação do Artefato First Things First
  docs/firstthingsfirst.md
  mkdocs.yml
Labels: documentation, elicitação

#18 5 w2 h
  docs/5w2h.md
  mkdocs.yml
Labels: documentation, pré-rastreabilidade

#21 Add speech analysis document
  docs/analisediscurso.md
  docs/assets/analisediscurso-peopletalking.png
  mkdocs.yml
Labels: documentation, elicitação

#26 Melhorias solicitadas no Ponto de Controle 2
  docs/assets/moscow.png
  docs/ata_24_08_2021.md
  docs/cronograma.md
  docs/elicitacao/moscow.md
  docs/firstthingsfirst.md
  docs/personas.md
  mkdocs.yml
Labels: documentation, priorização

#36 27 especificacaosuplementar
  docs/assets/tesouro-direto-logo-withoutback.png
  docs/especificacaosuplementar.md
  mkdocs.yml
Labels: documentation, modelagem

#37 31 lexico
  docs/modelagem/lexicos.md
Labels: documentation, modelagem

#38 Istar
  docs/assets/moscow.png
  docs/assets/tesouro-direto-logo-withoutback.png
  docs/ata_24_08_2021.md
  docs/casos_de_uso.md
  docs/cronograma.md
  docs/elicitacao/moscow.md
  docs/especificacaosuplementar.md
  docs/firstthingsfirst.md
  docs/modelagem/cenarios.md
  docs/modelagem/lexicos.md
  docs/personas.md
  mkdocs.yml
Labels: documentation, modelagem
